/**
 * @summary Entity that represents an alert or event generated by SafeHome.
 * @author SofTech
 */
export interface SecurityEventEntity {
  id: string;
  title: string;
  device: string;
  zone: string;
  type: 'intrusion' | 'battery' | 'camera' | 'lock' | 'system' | 'smoke';
  severity: 'critical' | 'medium' | 'info' | 'resolved';
  status: 'active' | 'attended' | 'resolved';
  createdAt: string;
  description: string;
}
